name: disney_plus_replica
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-55.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  get_it: ^7.6.0
  json_serializable: ^6.7.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/movies.json
    - assets/images/logos/
    - assets/images/movies/avengers/
    - assets/images/movies/avengers_age_of_ultron/
    - assets/images/movies/avengers_infinity_war/
    - assets/images/movies/avengers_endgame/
    - assets/images/movies/shang_chi_legend_of_the_ten_rings/
    - assets/images/movies/wanda_vision/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700